apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:            
        app: nodejs
    spec:
      containers:
        - image: node:latest
          name: nodejs
          command: ["node", "-e", "console.log('Hello World!')"]
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB
              value: MONGODB
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  labels:                     
    app: nodejs
spec:
  ports:                     
    - port: 3000
      targetPort: 3000
  selector:
    app: nodejs
  type: LoadBalancer






